package com.bangkit.composeapp.model

import androidx.compose.ui.input.key.Key.Companion.I
import com.bangkit.composeapp.R
import com.bangkit.composeapp.model.FakeProductDataSource.dummyProducts
import kotlin.random.Random

object FakeProductDataSource {
    val dummyProducts = listOf(
        Product(1, R.drawable.book_a_little_princess,"A Little Princess", 488, "Frances Hodgson Burnett", "Sara Crewe, a pupil at Miss Minchin's London school, is left in poverty when her father dies, but is later rescued by a mysterious benefactor."),
        Product(2, R.drawable.book_the_picture_of_dorian_gray, "The Picture of Dorian Gray", 488, "Oscar Wilde", "A gothic melodrama full of subtle impression and epigram, which tells a story about moral corruption. The Picture of Dorian Gray touches on many of Wilde's recurring themes, such as the nature and spirit of art, aestheticism and the dangers inherent to it."),
        Product(3, R.drawable.book_sherlock_holmes_retold_for_children,"Sherlock Holmes Retold for Children: 16 Books",14750, "Alex Wolf", "Join world-famous detective Sherlock Holmes and his ever-loyal sidekick Dr. Watson as they embark on a series of daring adventures. Priceless jewels disappear from a hotel suite, a monstrous hound is spotted on the moors and a woman is murdered in a locked room. Can our brilliant hero solve these mysteries and more before disaster strikes?"),
        Product(4, R.drawable.book_the_bodyguard,"The Bodyguard: A Novel", 133830, "Katherine Center", "Katherine Center's The Bodyguard is “My perfect 10 of a book. As funny and sweet as all the very best nineties rom-coms, but with Center’s signature heart-tugging depth. I wish I could erase it from my mind just to read it again for the first time. A shot of pure joy.”—Emily Henry, #1 New York Times bestselling author of Book Lovers"),
        Product(5, R.drawable.book_the_stand_in,"The Stand-In", 173534, "Lily Chu", "Gracie Reed was just fired by her overly \"handsy\" boss at the worst possible moment. She's been scraping together every extra dollar to get her mother into a top-notch memory care center. To make matters worse, a paparazzo has mistaken her for a famous Chinese actress in town for a new project and the resulting snapshot's gone viral. Gracie's barely holding it all together...until a mysterious SUV rolls up beside her on the street, and she's offered the opportunity of a lifetime."),
        Product(6, R.drawable.book_my_fault,"My Fault", 108888,"Mercedes Ron", "Seventeen-year-old Noah Morgan loves her quiet, normal life in Toronto. But when her mother returns from a cruise unexpectedly married to a billionaire and announces they are moving to L.A., Noah is suddenly shoved out of her comfort zone and into a glittering world of illegal street races, lavish pool parties, and spoiled rich kids."),
        Product(7, R.drawable.book_love_theoretically,"Love, Theoretically", 98320,"Ali Hazelwood", "The many lives of theoretical physicist Elsie Hannaway have finally caught up with her. By day, she’s an adjunct professor, toiling away at grading labs and teaching thermodynamics in the hopes of landing tenure. By other day, Elsie makes up for her non-existent paycheck by offering her services as a fake girlfriend, tapping into her expertly honed people-pleasing skills to embody whichever version of herself the client needs."),
        Product(8, R.drawable.book_the_alchemist,"The Alchemist", 151327,"Paulo Coelho", "Combining magic, mysticism, wisdom and wonder into an inspiring tale of self-discovery, The Alchemist has become a modern classic, selling millions of copies around the world and transforming the lives of countless readers across generations."),
        Product(9, R.drawable.book_legally_blonde,"Legally Blonde", 35732,"Amanda Brown", "The funny romantic comedy about an unlikely law student with big dreams that inspired the blockbuster movie and the Broadway musical."),
        Product(10, R.drawable.book_dinosaur_who_lost,"The Dinosaur who lost his roar", 48774,"Russell Punter", "Sid likes scaring his friends with his mighty roar, but when Sid loses his voice, will his friends wish he hadn’t? Specially written for children beginning to read alone, with delightful audio narration."),
        Product(11, R.drawable.book_psychology_of_money,"The Psychology of Money", 161452,"Morgan Housel", "Doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people."),
        Product(12, R.drawable.book_percy_jackson,"Percy Jackson and the Lightning Thief", 113839,"Rick Riordan", "I was just a normal kid, I went to school (got expelled a lot, but that wasn't my fault), played sports and hung out with my best friend. Until I accidentally vaporized my maths teacher.Now, I spend my time at Camp Half Blood, battling monsters and generally trying to stay alive. And now that Zeus thinks I've stolen his lightning bolt, staying alive is going to be even harder..."),
        Product(13, R.drawable.book_pathless_path,"The Pathless Path", 112458,"Paul Millerd", "This Pathless Path is about finding yourself in the wrong life, and the real work of figuring out how to live. Through painstaking experiments, living in different countries, and contemplating the deepest questions about life, Paul pieces together a set of ideas and principles that guide him from unfulfilled and burned out to a life he is excited to keep living."),
        Product(14, R.drawable.book_good_vibes,"Good Vibes, Good Life", 145711,"Vex King", "Join the self-love revolution with Instagram visionary Vex King. This limited-edition hardback includes inspirational messages, beautiful illustrations and universal wisdom to help you manifest positive vibes."),
        Product(15, R.drawable.book_ikigai,"Ikigai", 117923,"Penguin", "According to the Japanese, everyone has an ikigai—a reason for living. And according to the residents of the Japanese village with the world’s longest-living people, finding it is the key to a happier and longer life."),
        Product(16, R.drawable.book_design_thinking,"The Design Thinking Life Playbook", 335708,"Michael Lewrick, Jean-Paul Thommen, dan Larry Leifer", "The Design Thinking Life Playbook is for anyone who wants to have a fulfilling and joyful future. Its for all those who want to initiate change through self-empowerment and have the courage to think, act, and take advantage of their opportunities proactively."),
        Product(17, R.drawable.book_all_you_need,"All You Need is Less", 51623,"Vicki Vrint", "We live such busy lives, rushing from one thing to the next, that we barely give ourselves time to catch our breath. But what would happen if we aimed for less?"),
        Product(18, R.drawable.book_the_wicked,"The Wicked In Me", 277723,"Suzanne Wright", "No one really knows what they are. Only that they're the first civilization. Aeons, they call themselves. They're immortal. Powerful. Secretive."),
        Product(19, R.drawable.book_ice_breaker,"Icebreaker", 112771,"Hannah Grace", "Anastasia Allen has worked her entire life for a shot at Team USA. It looks like everything is going according to plan when she gets a full scholarship to the University of California, Maple Hills and lands a place on their competitive figure skating team."),
        Product(20, R.drawable.book_bridgerton,"Bridgerton: The Duke and I", 142853,"Julia Quinn", "In the ballrooms and drawing rooms of Regency London, rules abound. From their earliest days, children of aristocrats learn how to address an earl and curtsey before a prince—while other dictates of the ton are unspoken yet universally understood. A proper duke should be imperious and aloof. A young, marriageable lady should be amiable…but not too amiable."),
        Product(21, R.drawable.book_aunties,"Dial A for Aunties", 70822,"Jesse Q. Sutanto", "What happens when you mix 1 (accidental) murder with 2 thousand wedding guests, and then toss in a possible curse on 3 generations of an immigrant Chinese-Indonesian family?"),
        Product(22, R.drawable.book_chase_me,"Chase Me", 97306,"Tessa Bailey", "College drop-out Roxy Cumberland moved to New York with dreams of becoming an actress, but her dwindling bank account is quickly putting the kibosh on that fantasy."),
        Product(23, R.drawable.book_things_we_never,"Things We Never Got Over", 123598,"Lucy Score", "Escaping her seemingly perfect wedding, Naomi Witt arrives in rough-around-the-edges Knockemout, Virginia, running to the rescue of her estranged twin, Tina."),
        Product(24, R.drawable.book_beneath_the_moon,"Beneath the Moon", 72108,"Yoshi Yoshitani", "Powerful and universal retellings of seventy-eight divine stories, legends, and myths from around the world, each accompanied by a gorgeous illustration from acclaimed artist Yoshi Yoshitani."),
        Product(25, R.drawable.book_twice_in,"Twice in a Blue Moon", 104465,"Christina Lauren", "During a whirlwind two-week vacation abroad, Sam and Tate fell for each other in only the way that first loves do: sharing all of their hopes, dreams, and deepest secrets along the way."),
        Product(26, R.drawable.book_it_ends_with_us,"It Ends with Us", 146633,"Colleen Hoover", "Lily hasn’t always had it easy, but that’s never stopped her from working hard for the life she wants. She’s come a long way from the small town where she grew up—she graduated from college, moved to Boston, and started her own business. And when she feels a spark with a gorgeous neurosurgeon named Ryle Kincaid, everything in Lily’s life seems too good to be true."),
        Product(27, R.drawable.book_it_starts_with_us,"It Starts with Us", 157920,"Colleen Hoover", "Lily and her ex-husband, Ryle, have just settled into a civil coparenting rhythm when she suddenly bumps into her first love, Atlas, again. After nearly two years separated, she is elated that for once, time is on their side, and she immediately says yes when Atlas asks her on a date."),
        Product(28, R.drawable.book_all_your_perfects,"All Your Perfects", 146633,"Colleen Hoover", "Quinn and Graham’s perfect love is threatened by their imperfect marriage. The memories, mistakes, and secrets that they have built up over the years are now tearing them apart. The one thing that could save them might also be the very thing that pushes their marriage beyond the point of repair."),
        Product(29, R.drawable.book_batman,"Batman: Year One", 168579,"Frank Miller dan David Mazzucchelli", "A new edition of one of the most important and critically acclaimed Batman adventures ever, written by Frank Miller, author of THE DARK KNIGHT RETURNS!"),
        Product(30, R.drawable.book_scaredy_cat,"The Scaredy Cat", 65032,"Russell Punter", "Stanley is a cat who’s scared of everything, so a dark house full of strange noises is the last place he wants to be. Can Stanley face his fears and save the day?"),
    )
}


